src/tinyshop/frontend/urls.py
from django.conf.urls.defaults import patterns, url

from tinyshop.frontend.views import CategoryView, ProductCreateView, ProductView


urlpatterns = patterns('tinyshop.frontend.views',
    url(r'^$', CategoryView.as_view(), {'parent': None}, name='category_root'),
    url(r'^category/(?P<parent>[^/]+)/$', CategoryView.as_view(), name='category_list'),
    url(r'^product/(?P<parent>[^/]+)/new/$', ProductCreateView.as_view(), name='product_create'),
    url(r'^product/(?P<slug>[^/]+)/$', ProductView.as_view(), name='product_detail'),
)

src/tinyshop/urls.py
from django.conf.urls.defaults import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('tinyshop.frontend.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

src/tinyshop/frontend/models.py
from collections import defaultdict
from django.utils.translation import gettext_lazy as _
from django.db import models
from django import forms

class Category(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
    
    parent = models.ForeignKey('Category', null=True, blank=True)
    
    def is_leaf(self):
        return not bool(self.category_set.all())
    
    def parents(self):
        if self.parent:
            yield self.parent
            for parent in self.parent.parents():
                yield parent
    
    def __unicode__(self):
        return self.title
    
    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')
        ordering = 'title',
    
class Product(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
    
    category = models.ForeignKey(Category)
    
    def get_custom_fields(self):
        '''
        Returns list of custom fields with an value object, ordered by name
        '''
        fields = defaultdict(lambda: [])
        # group for speed up db searches
        for field in list(self.category.customfield_set.all()):
            fields[field.get_field_model()].append(field)
        data = []
        # get data from db
        for model, custom_fields in fields.iteritems():
            fields = dict((f.id, f) for f in custom_fields)
            for value in model.objects.filter(custom_field__in=custom_fields, product=self):
                data.append((fields.get(value.custom_field_id), value))
                
        # order by name
        return sorted(data, key=lambda data: data[0].name)
      
    def set_custom_field(self, custom_field, value):
        '''
        Set custom field of model, there is not test for case when product do not have value of
        selected custom_field. Testing this will take databese query, this is tested on form level
        If you force to set wrong custom_field data will be not shown from the get_custom_field.
        '''
        model = custom_field.get_field_model()
        custom_value, created = model.objects.get_or_create(custom_field=custom_field, product=self, defaults={'value': value})
        if not created:
            custom_value.value = value
            custom_value.save()
    
    def get_custom_field(self, custom_field):
        model = custom_field.get_field_model()
        return model.objects.get(custom_field=custom_field, product=self)
    
    def __unicode__(self):
        return self.title
    
    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')
        ordering = 'title',

# custom fields part

class CustomField(models.Model):
    '''
    Definition of custiom fields, object of this model is 
    connected with category. Objects added to the category 
    are using this custom fields
    '''
    TYPE_INTEGER, TYPE_BOOL, TYPE_TEXT = range(3)
    TYPES = (
        (TYPE_INTEGER, _('integer')),
        (TYPE_BOOL, _('bool')),
        (TYPE_TEXT, _('text'))
    )
    category = models.ForeignKey('Category')
    name = models.CharField(max_length=250)
    type = models.IntegerField(choices=TYPES)
    
    def get_field_class(self):
        '''
        Returns field class, used to generate form
        '''
        return TYPE2FIELD_CLASS.get(self.type)(label=self.name)

    def get_field_model(self):
        '''
        Returns field model class, used to prepare queryset
        '''
        return TYPE2FIELD_MODEL.get(self.type)
        
    def __unicode__(self):
        return u'%s - %s' % (self.name, self.category)
 
class CustomFieldValueBase(models.Model):
    '''
    Common part of models which are storing value of
    custom fields, for every type of custom field there is
    a different model.
    Value models must have a field value which stores 
    the value of fields in selected type
    '''
    custom_field = models.ForeignKey(CustomField, related_name="%(app_label)s_%(class)s_related")
    product = models.ForeignKey(Product)
    
    class Meta:
        unique_together = ('custom_field', 'product')
        abstract = True
        
class IntegerValue(CustomFieldValueBase):
    value = models.IntegerField()
    
    def __unicode__(self):
        v = unicode(self.value)
        # and here is a joke
        return ' '.join(list((v[::-1][x:x + 3][::-1] for x in range(0, len(v), 3)))[::-1])
    
class BoolValue(CustomFieldValueBase):
    value = models.BooleanField()
    
    def __unicode__(self):
        if self.value:
            return unicode(_('Yes'))
        else:
            return unicode(_('No'))
    
class TextValue(CustomFieldValueBase):
    value = models.TextField()
    
    def __unicode__(self):
        return self.value

# definition classes and models of types 
# TYPE2FIELD_CLASS - is a dictionary which maps type of 
#    custom field to form field class, or to delegate of this class
# TYPE2FIELD_MODELS - maps type to  model class for values of this type
TYPE2FIELD_CLASS = {
    CustomField.TYPE_INTEGER: forms.IntegerField,
    CustomField.TYPE_BOOL: lambda * args, **kwargs: forms.BooleanField(*args, required=False, **kwargs),
    CustomField.TYPE_TEXT: lambda * args, **kwargs: forms.CharField(*args, widget=forms.Textarea, **kwargs)
}

TYPE2FIELD_MODEL = {
    CustomField.TYPE_INTEGER: IntegerValue,
    CustomField.TYPE_BOOL: BoolValue,
    CustomField.TYPE_TEXT: TextValue,
}

src/tinyshop/frontend/forms.py
from django import forms
from django.forms.models import ModelFormMetaclass

from tinyshop.frontend.models import Product, Category


class ProductFormMetaBase(ModelFormMetaclass):
    '''
    Metaclass used to generate form fields for custom_field in product form
    '''
    def __new__(cls, name, bases, attrs):
        if 'custom_fields' in attrs:
            custom_fields = {}
            for custom_field in attrs.get('custom_fields'):
                key = 'custom_field_%d' % custom_field.id
                attrs[key] = custom_field.get_field_class()
                custom_fields[key] = custom_field
            attrs['custom_fields'] = custom_fields
        
        return ModelFormMetaclass.__new__(cls, name, bases, attrs)

class ProductFormBase(forms.ModelForm):
    '''
    Class to overide metaclass of modelform, and save values of custom fields
    '''
    __metaclass__ = ProductFormMetaBase
    
    def save(self, *args, **kwargs):
        instance = super(ProductFormBase, self).save(*args, **kwargs)
        for key, custom_field in self.custom_fields.iteritems():
            instance.set_custom_field(custom_field, self.cleaned_data.get(key))
        return instance

def ProductFormFactory(category):
    '''
    Factory of product form for selected category. Form will have and field for custom fields used in
    this category
    '''
    custom_fields_ = list(category.customfield_set.all())
    
    class ProductForm(ProductFormBase):
        custom_fields = custom_fields_ 
        category = forms.ModelChoiceField(queryset=Category.objects.all(), widget=forms.HiddenInput)
        
        class Meta:
            model = Product
            
    return ProductForm

src/tinyshop/frontend/views.py
# Create your views here.
from django.views.generic.list import ListView, MultipleObjectMixin
from django.shortcuts import get_object_or_404
from django.views.generic.edit import CreateView
from django.views.generic.detail import SingleObjectMixin, DetailView
from django.core.urlresolvers import reverse

from tinyshop.frontend.forms import ProductFormFactory
from tinyshop.frontend.models import Category, Product


class CategoryListBaseMixIn(object):
    def get_context_data(self, **kwargs):
        context = super(CategoryListBaseMixIn, self).get_context_data(**kwargs)
        context.update(category=self.get_current_category())
        return context
    
    def get_current_category(self):
        if not hasattr(self, '_current_category'):
            parent = self.kwargs.get('parent')
            if parent:
                self._current_category = get_object_or_404(Category, slug=parent)
            else:
                self._current_category = None
        return self._current_category

class CategoryListMixIn(CategoryListBaseMixIn, MultipleObjectMixin):
    pass

class CategoryViewMixIn(CategoryListBaseMixIn, SingleObjectMixin):
    pass

class CategoryView(ListView, CategoryListMixIn):
    def get_queryset(self):
        parent = self.get_current_category()
        if parent:
            return parent.category_set.all()
        else:
            return Category.objects.filter(parent=None)

class ProductView(CategoryViewMixIn, DetailView):
    queryset = Product.objects.all()
    
    def get_current_category(self):
        return self.get_object().category
    
class ProductCreateView(CategoryViewMixIn, CreateView):
    model = Product
    
    def get_form_class(self):
        return ProductFormFactory(self.get_current_category())
    
    def get_success_url(self):
        return reverse('category_list', kwargs={'parent': self.kwargs.get('parent')})
    
    def get_initial(self):
        return {'category': self.get_current_category()}

src/tinyshop/frontend/templates/frontend/_broadscrum_list.html
{% load i18n %}
{% if category %}
<nav class="parents">
    <ul class="broadcrum">
    <li><a href="{% url category_root %}">{% trans "Root" %}</a></li>
    {% for parent in category.parents %}
        <li><a href="{% url category_list parent=parent.slug %}">{{ parent }}</a></li>
    {% endfor %}
    {% if object or form %}
        <li><a href="{% url category_list parent=category.slug %}">{{ category }}</a></li>
    {% endif %}
    </ul>
    <div class="clear"></div>
</nav>
{% endif %}

src/tinyshop/frontend/templates/frontend/category_list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<section class="container">
    {% include "frontend/_broadscrum_list.html" %}
    <h2>{% if category %}{% blocktrans with category as category %}Subcategories of {{ category }}{% endblocktrans %}{% else %}{% trans "Root category" %}{% endif %}</h2>
</section>
<hr/>
<section class="container subcategories">
{% if object_list %}
    <h3>{% trans "Subcategories" %}</h3>
    <nav>
    <ul>
    {% for category in object_list %}
        <li><a href="{% url category_list parent=category.slug %}">{{ category }}</a></li>
    {% empty %}
        {% trans "No subcategories in this category" %}
    {% endfor %}
    </ul>
    </nav>
{% else %}
    {% if category %}
        <h3>{% trans "Products in this category" %}</h3>
        <nav>
        <ul>
            {% for product in category.product_set.all %}
                <li><a href="{% url product_detail slug=product.slug %}">{{ product }}</a></li>
            {% empty %}
                {% trans "No products in this category" %}
            {% endfor %}
        </ul>
        </nav>
        <a class="clear" href="{% url product_create parent=category.slug %}">{% trans "Add new product" %}</a>
     {% endif %}
{% endif %}
</section>
{% endblock %}

src/tinyshop/frontend/templates/frontend/product_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<article class="container">
{% include "frontend/_broadscrum_list.html" %}
<h2>{% if category %}{% blocktrans with object as product %}Detail of {{ product }}{% endblocktrans %}{% else %}{% trans "Root category" %}{% endif %}</h2>
<h3>{{ object }}</h3>
<dl>
    {% for field, value in object.get_custom_fields %}
    <dt>{{ field.name }}</dt>
    <dd>{{ value }}</dd>
    {% endfor %}
</dl>
</article>
{% endblock %}

src/tinyshop/frontend/templates/frontend/product_form.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<section class="container">
{% include "frontend/_broadscrum_list.html" %}
<h2>{% if category %}{% blocktrans with category as category %}New product in category {{ category }}{% endblocktrans %}{% else %}{% trans "Root category" %}{% endif %}</h2>
<form action="" method="post">
    {% csrf_token %}
    <legend>{% trans "Add new product" %}</legend>
    <fieldset>
    <dl>
    {% for field in form %}
        {% if field.is_hidden %}
            {{ field }}
        {% else %}
        {% if field.errors %}
            <div class="error span-24 last">        
            {{ field.errors }}
            </div>
        {% endif %}
            <dt>{{ field.label_tag }}:</dt>
            <dl>{{ field }}</dl>
        {% endif %}
    {% endfor %}
    </dl>
      <button type="submit" class="button positive">
        <img src="{{ STATIC_URL }}css/blueprint/plugins/buttons/icons/tick.png" alt=""/> Save
      </button>
    </fieldset>
</form>
</section>
{% endblock %}